name: Notify Telegram on Release

on:
  release:
    types: [published]

jobs:
  notify:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram Notification
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=🎉 芝麻粒 [${{ github.event.release.tag_name }}](${{ github.event.release.html_url }}) 已发布🚀%0A%0A${{ github.event.release.body }}" \
          -d "parse_mode=Markdown"
